spring:
  application:
    name: redis-example
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:tcp://localhost/~/test
      username: user
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /redis-example