server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serailizer: org.apache.kafka.common.serialization.StringSerializer

